### PR TITLE
[WIP] Initial makeClient sketch

### PR DESCRIPTION
**Pull request by xplosunn**

### CODE REVIEW

**Review by jdegoes — DISMISSED** [review]

**Comment by jdegoes** [comment]
@xplosunn Looks good, can you run fmt and we can merge it in? I know it's just a sketch but it's better than what exists there already and is a step in the right direction!

**Comment by jdegoes** [comment]
@xplosunn Just touching base here. Do you think you'll have a chance to format the code?

**Comment by xplosunn** [comment]
@jdegoes Done

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Thank you!

**Comment by jdegoes** [comment]
Had to revert as it did not compile.

**Pull request merged**
