### PR TITLE
Issue 73

### PR DESCRIPTION
**Pull request by brbrown25**

### CODE REVIEW

**Comment by brbrown25** [comment]
This is a WIP pr to make it easier to see the work being done.

**Comment by brbrown25** [comment]
> The java.time generators are too good and keep finding bugs in zio-json 😄. I'm wondering if `JavaTimeGen` could go in `zio-test` (they actually need there own tests). It would be nice to use them from zio-json too.
> 
> 
> 
> `SchemaGen` and `StandardTypeGen` ought to go into zio-schema now that it lives elsewhere. There are some tricky parts there that I'm not sure how to solve yet.

Yeah that makes sense. I know there's a ticket for adding support for other formatters for java time. Currently it's expecting everything in ISO format.

**Comment by jdegoes** [comment]
@brbrown25 This looks great! Can you move it over to the ZIO Schema project (zio/zio-schema)?

**Comment by brbrown25** [comment]
> @brbrown25 This looks great! Can you move it over to the ZIO Schema project (zio/zio-schema)?

Yes I'll do so tomorrow!

**Comment by jdegoes** [comment]
Closing this here, will merge in ZIO Schema.

**Pull request closed without merging**
